# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:22.8.0
    steps:
      - checkout
      - run:
          command: npm install
      - run:
          command: npm run build
  test:
    docker:
      - image: mcr.microsoft.com/playwright:focal
    steps:
      - checkout
      - run:
          command: npm install
      - run:
          command: '(npm run dev&); sleep 1; npm run test:e2e'
          environment:
            CI: 1

workflows:
  calculatall-flow:
    jobs:
      - build
      - test:
          requires:
            - build
