# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  check_version_increment:
    docker:
      - image: cimg/node:23.3.0
    steps:
      - checkout
      - run:
          command: |
            export TAG=$(git tag --sort=version:refname | tail -1);
            export CURRENT_VERSION=$(cat package.json | grep version | sed -n 's/.*\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p');
            if [ "$TAG" = "$CURRENT_VERSION" ]; then exit 1; fi;
  build:
    docker:
      - image: cimg/node:23.3.0
    steps:
      - checkout
      - run:
          command: npm install
      - run:
          command: npm run build

  update_tag:
    docker:
      - image: cimg/node:23.3.0
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:fvYT5h4xTcxm8rTqKYhAkbWRCpnt+ydR7XlBxiiNelU"
      - checkout
      - run:
          command: |
            git config --global user.email "ymamykin@gmail.com";
            git config --global user.name "YarikMamykin";
            export NEW_TAG=$(cat package.json | grep version | sed -n 's/.*\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p'); 
            git tag -a $NEW_TAG -m $NEW_TAG; 
            git push origin --tags;

  # test:
  # docker:
  # - image: mcr.microsoft.com/playwright:focal
  # steps:
  # - checkout
  # - run:
  # command: npm install
  # - run:
  # command: '(npm run dev&); sleep 1; npm run test:e2e'
  # environment:
  # CI: 1

workflows:
  calculatall-flow:
    jobs:
      - check_version_increment:
          filters:
            branches:
              ignore: main
      - build
      - update_tag:
          filters:
            branches:
              only:
                - main
      # - test:
      # requires:
      # - build
